authors:
  seth:
    name: Seth Juarez
    description: Principal AI PM, Microsoft
    avatar: https://github.com/sethjuarez.png
  nitya:
    name: Nitya Narasimhan
    description: Senior AI Advocate, Microsoft
    avatar: https://github.com/nitya.png
  bethany:
    name: Bethany Jepchumba
    description: AI Advocate, Microsoft
    avatar: https://github.com/bethanyjep